//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUDash.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string Id { get; set; }
        public string ResourceId { get; set; }
        public string ProjectId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ATBApproval { get; set; }
        public Nullable<System.DateTime> ATBApprovalSentOn { get; set; }
        public byte[] InvoiceRaised { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceRaisedOn { get; set; }
        public string Comments { get; set; }
        public byte[] PaymentReceived { get; set; }
        public string EngagementNumber { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
